### ISSUE TITLE
Reducing the number of nodes

### ISSUE THREAD

**Issue by webD97** [minetest-streets/streets#101]
Thsi is my suggestion to reduce the number of asphalt nodes in this mod:

- Only register the stair and slab in the main mod, for full stairs+ support there should be a separate mod with an explicit warning about the number of nodes being registered

Advantages:
- Stairs development can be done seperately without requiring updates to the core mod (some kind of microservice architecture)

Disadvantages:
- Users will need to download a separate mod

**Comment by Thomas--S** [comment]
I will try to rewrite parts of the stairsplus code, so that we are able to only register the really needed nodes. This will also reduce the number of nodes drastically.

I think choosing between stairs and stairsplus should be done with a setting, not with a separate mod. This will be simpler for developers and users.

**Comment by Thomas--S** [comment]
You can follow my progress on modifying stairsplus here: https://github.com/Thomas--S/moreblocks/tree/custom

There isn't much to see yet.

I'll submit those modifications as a PR when I'm ready.

**Comment by Thomas--S** [comment]
The modifications of the moreblocks mod should be ready now. You can see them here: https://github.com/Thomas--S/moreblocks/tree/custom

I'll submit these as a PR when I am ready with testing.

**Comment by Thomas--S** [comment]
At the moment, we have three types of signs: center, polemount and normal.

@webD97 What's your opinion on removing the center ones?

**Comment by webD97** [comment]
What do you mean by "center"?

**Comment by Thomas--S** [comment]
Combinations like this:

![](https://camo.githubusercontent.com/a3bb45230e1c522ec479541e2df04c98aef6bf72/687474703a2f2f692e696d6775722e636f6d2f6c5452663673462e706e67)


Where the sign is directly placed on top of a pole without a pole behind the sign.

This combination is quite unrealistic in my opinion and only rarely used, so I think we should remove those centered signs.

**Comment by webD97** [comment]
Okay, now I see what you mean. I fully support getting rid of this stlye...

**Comment by Thomas--S** [comment]
I think this can be closed now: f17617e9b36a8742f0af8c2bed0b476942f4774f

There is a new setting called `streets.roadmarkings_stairs_variations`, which can either be `limited`, `normal` or `full`. `normal` is the default.

This leads to following node numbers

| Setting | Number of nodes |
|---|---|
| `limited` | ~500 |
| `normal` | ~1350 |
| `full` | ~8000 |
