### ISSUE TITLE
Make use of kaeza's intllib

### ISSUE THREAD

**Issue by webD97** [minetest-streets/streets#54]
Implement intllib and supply a template file for translators.

**Comment by Thomas--S** [comment]
Does this really make sense?
First of all, making everything translatable is a lot of work.
Secondly, translations are server-side, so most of the time, English (the default) will be used. As a result, our translations only have little use.
Finally, many things aren't even translatable, e.g. road signs.

I suggest to not provide support for the intllib, as the amount of work is too high for the little use.

I'm looking forward to hear your opinions.

**Comment by Thomas--S** [comment]
I suggest to use the new client-side translations as soon as 0.5.0 is stable.

**Comment by webD97** [comment]
That would be the best option.
