### ISSUE TITLE
Support for visual_scale in streets.register_road_sign()

### ISSUE THREAD

**Issue by webD97** [minetest-streets/streets#80]
Especially highway signs need to be bigger than 1m. An optional field for the visual_scale would be perfect, but that would require the use of a mesh instead of nodeboxes, see [Minetest API](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3488)

**Comment by Thomas--S** [comment]
I also suggest to support `light_source`.

**Comment by Thomas--S** [comment]
And the `visual_scale` problem can be fixed when using nodeboxes that are bigger than a node.

**Comment by webdesigner97** [comment]
But that would tile the texture instead of scaling it...

**Comment by Thomas--S** [comment]
d8ec7f619155bdea71c23cfa8e37e1dc250350c9
