### ISSUE TITLE
Support for half-height blocks

### ISSUE THREAD

**Issue by fireglow** [minetest-streets/streets#88]
Hi, just been testing the relaunch branch and all my players liked it, we're especially fond of the great selection of signs and markings.
However, we can't use this mod on our main server for now because the various streets: blocks cannot align with half-height blocks like slabs. (We use slabs extensively to mimic curbstones)
Is this something that can be fixed in the future?

**Comment by webdesigner97** [comment]
We also noticed this problem some months ago and found that it is a problem with minetest_game if I remember correctly. There was an issue discussing this, But to be honest, I don't remember if it was resolved because I'm quite inactive these days (job)...

**Comment by fireglow** [comment]
Ah, I see.
Maybe @cheapie has more information on the subject?

**Comment by webD97** [comment]
I'll investigate if this is still happening.

**Comment by webD97** [comment]
Seems to be fixed.
