### ISSUE TITLE
Crash on startup if mesecons not installed

### ISSUE THREAD

**Issue by webD97** [minetest-streets/streets#89]
The game crashes on startup, if mesecons is not installed due to missing `mesecon `table: https://github.com/minetest-streets/streets/blob/master/streets_bollards/init.lua#L35

**Comment by Thomas--S** [comment]
I will try to fix this ASAP

**Comment by Thomas--S** [comment]
27eedcb

**Comment by webD97** [comment]
Thank you, I would do this myself, but I'm busy.

**Comment by Thomas--S** [comment]
Thanks for reporting the bug!
