### ISSUE TITLE
Hanging light same recipe with horizontal light

### ISSUE THREAD

**Issue by darkfeels** [minetest-streets/streets#90]
Hello,

I've download the "new" streets mod and saw that I must build alle my streets new :/
While I was bulding the street latern new I noticed that the Horizontal street light has the same recipe like the Hanging streets light.
I'd tried to build booth of the lights but every time I only got the hanging version of the light.

`
minetest.register_craft({
	output = "streets:light_horizontal_off 3",
	recipe = {
		{"", "", ""},
		{"default:steel_ingot", "default:meselamp", "default:steel_ingot"},
		{"", "", ""}
	}
})

minetest.register_craft({
	output = "streets:light_hanging_off 3",
	recipe = {
		{"default:steel_ingot", "default:meselamp", "default:steel_ingot"},
		{"", "", ""},
		{"", "", ""}
	}
})`

Maybe could be this the solution:

`})

minetest.register_craft({
	output = "streets:light_hanging_off",
	recipe = {
		{"", "", ""},
		{"", "streets:light_hanging_off", ""},
		{"", "", ""}
	}
})``

So I only need to produce the "normal" horizontal one and if I want to produce the hanging one I only need to put one of the hanging one in the craft window and I get the hanging on.

**Comment by Thomas--S** [comment]
8fff7db
