### ISSUE TITLE
No concrete recipe without Technic Mod

### ISSUE THREAD

**Issue by darkfeels** [minetest-streets/streets#91]
There is no recipe for concrete without the Technic mod.
Maybe we could use the "old" recipe:

{ "", "", "" },
{ "", "default:stone ", "" },
{ "", "", "" }

**Comment by Thomas--S** [comment]
Thanks for the report. I used a slightly different recipe:

```lua
minetest.register_craft({
	output = "streets:concrete 5",
	recipe = {
		{ "default:steel_ingot", "default:stone", "default:steel_ingot" },
		{ "default:stone", "default:steel_ingot", "default:stone" },
		{ "default:steel_ingot", "default:stone", "default:steel_ingot" },
	}
})
```

db6f05b186d25358cba21f1b3c35979ca08d199a

**Comment by webD97** [comment]
I'm not sure if this recipe is optimal... Using steel for non-reinforced concrete seems weird. Also a 3x3 recipe means a lot of work for such a "basic" node. We should at least reduce the size to 2x2.
However, I'd prefer a completely new recipe that involves e.g. mixing stone and sand. I'll think about this later...
